USE [master]
GO

/****** Object:  Database [MINDWORX_AlumniAppDB]    Script Date: 2021/06/04 12:41:18 ******/
CREATE DATABASE [MINDWORX_AlumniAppDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MINDWORX_AlumniAppDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL_EXPRESS\MSSQL\DATA\MINDWORX_AlumniAppDB.mdf' , SIZE = 15360KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MINDWORX_AlumniAppDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL_EXPRESS\MSSQL\DATA\MINDWORX_AlumniAppDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MINDWORX_AlumniAppDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET RECOVERY FULL 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET  MULTI_USER 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET QUERY_STORE = OFF
GO

USE [MINDWORX_AlumniAppDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [MINDWORX_AlumniAppDB] SET  READ_WRITE 
GO

